# Generated by Django 5.2.4 on 2025-07-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='livepeer_playback_url',
            new_name='livepeer_embed_url',
        ),
    ]
